In [2]:
import numpy as np

## 1.Create a null vector of size 10 but the fifth value which is 1.

In [7]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2. Create a vector with values ranging from 10 to 49.

In [8]:
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [72]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [70]:
arr = np.nonzero([1,2,0,0,4,0])
arr

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [31]:
arr = np.random.randint(0,100,(10,10))
arr

array([[87, 63, 90, 79, 61, 77, 80, 83, 95,  3],
       [65, 44, 37, 43, 29, 10,  2, 41, 37, 51],
       [79, 86, 59, 18, 47, 55, 95, 18, 83, 57],
       [59, 25, 66, 41, 96, 49, 46, 49, 42, 88],
       [64, 94, 42,  1, 71, 27,  6, 44,  2,  4],
       [91, 30, 32, 49, 10, 51, 31,  0, 63,  1],
       [68, 46, 65, 62, 50,  7, 88, 55, 45, 33],
       [59, 33, 28, 51, 23, 66, 86, 85, 43,  3],
       [20, 63, 85, 86, 86, 10, 26, 71, 60, 27],
       [58, 13, 50, 13, 21, 29, 15, 88, 50, 69]])

In [34]:
arr.min()

0

In [35]:
arr.max()

96

## 6. Create a random vector of size 30 and find the mean value.

In [79]:
vector = np.arange(30)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
vector.mean()

14.5